LYRICS = [
  "It's not simple to say that",
  "Most days, I don't recognise me",
  "That these shoes and this apron, that place and its patrons",
  "Have taken more than I gave them",
  "It's not easy to know I'm not anything",
  "Like I used to be, although it's true",
  "I was never attention's sweet center",
  "I still remember that girl",
  "She's imperfect, but she tries",
  "She is good, but she lies",
  "She is hard on herself",
  "She is broken and won't ask for help",
  "She is messy, but she's kind",
  "She is lonely most of the time",
  "She is all of this mixed up and baked in a beautiful pie",
  "She is gone, but she used to be mine",
  "",
  "It's not what I asked for",
  "Sometimes life just slips in through a back door",
  "And carves out a person who makes you believe it's all true",
  "And now I've got you",
  "You're not what I asked for",
  "If I'm honest I know I would give it all back for a chance",
  "To start over and rewrite an ending or two",
  "For the girl that I knew",
  "Who was reckless just enough",
  "Who gets hurt, but who learns how to toughen up",
  "When she's bruised and gets used by a man who can't love",
  "Then she'll get stuck and be scared",
  "Of the life that's inside her",
  "Getting stronger each day till it finally reminds her",
  "To fight just a little to bring back the fire in her eyes",
  "That's been gone, but used to be",
  "mine",
  "",
  "Used to be mine",
  "",
  "She is messy, but she's kind",
  "She is lonely most of the time",
  "She is all of this mixed up and baked in a beautiful pie",
  "She is gone, but she used to be",
  "mine."
]